# GenerateBuildStamp.cmake - Generates BuildStamp.h at build time
cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED OUTPUT_FILE)
    message(FATAL_ERROR "GenerateBuildStamp: OUTPUT_FILE must be defined")
endif()

if(DEFINED ENV{RELEASE_VERSION} AND NOT "$ENV{RELEASE_VERSION}" STREQUAL "")
    set(VERSION "$ENV{RELEASE_VERSION}")
elseif(DEFINED ENV{BETTERLUMA_VERSION} AND NOT "$ENV{BETTERLUMA_VERSION}" STREQUAL "")
    set(VERSION "$ENV{BETTERLUMA_VERSION}")
endif()

if(NOT DEFINED VERSION OR VERSION STREQUAL "")
    set(VERSION "debug")
endif()

get_filename_component(OUT_DIR "${OUTPUT_FILE}" DIRECTORY)
if(NOT EXISTS "${OUT_DIR}")
    file(MAKE_DIRECTORY "${OUT_DIR}")
endif()

string(TIMESTAMP BUILD_STAMP "%b %d %Y %H:%M:%S")

set(FILE_CONTENT "// Auto-generated by CMake build step. Do not edit directly.
#pragma once

#define BETTERLUMA_VERSION_STRING \"${VERSION}\"
#define BETTERLUMA_BUILD_STAMP_STRING \"${BUILD_STAMP}\"
")

# Always write to update timestamp and trigger compilation of BuildInfo.cpp
file(WRITE "${OUTPUT_FILE}" "${FILE_CONTENT}")
message(STATUS "Updated ${OUTPUT_FILE} (Version: ${VERSION}, Stamp: ${BUILD_STAMP})")
