// BetterLuma - Steam client hook layer.
// Modified from LumaCore, 2026.
// Distributed under the GNU General Public License v3 or later.
// Original work and copyright: see README.md.

#include "hooks/ui/SteamUI.h"
#include "core/Orchestrator.h"
#include "hooks/capture/RuntimeCapture.h"
#include "hooks/Macros.h"
#include "hooks/SigTypes.h"
#include "patterns/ByteScan.h"
#include "patterns/PatternFetcher.h"
#include "runtime/HookStatus.h"
#include "runtime/VehUtil.h"
#include "config/LuaLoader.h"
#include "hooks/client/StringFind.h"
#include "stats/GlobalAchievementManager.h"
#include "steam_messages.pb.h"

#include <psapi.h>

#include <algorithm>
#include <chrono>
#include <mutex>
#include <thread>
#include <unordered_set>
#include <vector>

namespace {
    using namespace std::chrono_literals;

    //  STEAMUI  function type aliases
    using AddProtobufAsBinary_t = void*(__fastcall*)(void* /*args*/, void* /*proto*/);
    using GetAppByID_t          = void*(__fastcall*)(void* /*controller*/, AppId_t, bool /*create*/);
    using GetTopManager_t       = void*(__fastcall*)();
    using MarkAppChange_t       = void*(__fastcall*)(void* /*source*/, AppId_t, uint32 /*EAppChangeFlags*/);
    using FillInAppOverview_t   = void*(__fastcall*)(void* /*pThis*/, void* /*pAppOverview*/, void* /*pApp*/);
    using BuildCompleteAppOverviewChange_t = void*(__fastcall*)(void* /*pController*/, void* /*pChange*/, void* /*optionalCallbackSlot*/);
    using CSteamUIAppControllerRunFrame_t  = void*(__fastcall*)(void* /*pController*/);
    using RepeatedFieldUint32_Add_t        = void(__fastcall*)(void* /*field*/, const uint32* /*value*/);

    //  STEAMUI  resolved function pointers
    // oAddProtobufAsBinary, oGetAppByID, oGetTopManager, oMarkAppChange,
    // oRepeatedFieldUint32_Add:
    //   MarkAppChange is now generated by LM_HOOK below; the rest stay manual
    //   since they are resolve-only helpers (no DetourAttach).
    inline AddProtobufAsBinary_t oAddProtobufAsBinary = nullptr;
    inline GetAppByID_t          oGetAppByID          = nullptr;
    inline GetTopManager_t       oGetTopManager       = nullptr;
    inline RepeatedFieldUint32_Add_t oRepeatedFieldUint32_Add = nullptr;

    // The CUpdateManager singleton instance used as the `this` argument to
    // MarkAppChange. Resolved in CoreHook from callsites in .text, or captured
    // from native calls in hkMarkAppChange.
    inline void* g_pAppChangeSource = nullptr;

    // ── Removal queue ──────────────────────────────────────────
    std::mutex g_removalMutex;
    std::mutex g_coreHookMutex;
    bool g_coreHookInstalled = false;
    std::vector<AppId_t> g_pendingRemovals;
    std::vector<AppId_t> g_pendingTouches;
    std::unordered_set<AppId_t> g_removedAppIds;

    // CSteamUIAppController offsets (see its Validate() method):
    //   +0xAB8 from top-manager -> CSteamUIAppController*
    //   +1744  m_vecAppOverviewChanged (subscriber vec data ptr)
    //   +1760  m_vecAppOverviewChanged size
    constexpr size_t kControllerInTopManager     = 0xAB8;
    constexpr size_t kSubscriberVecOffset        = 1744;
    constexpr size_t kSubscriberVecSizeOffset    = 1760;

    constexpr size_t kArgsSize                   = 64;
    constexpr size_t kSubscriberInvokeVtableSlot = 4;

    // Cleared so BuildCompleteAppOverviewChange's filter (BIsOwned via
    // vtable[22]) also excludes the app on the next full snapshot.
    constexpr size_t kCSteamAppOwnedFlagOffset   = 28;

    // TOML lookup-key candidates for AddProtobufAsBinary. The .xref field
    // carries the historical string-xref anchor that used to identify the
    // function before the TOML-only refactor; it stays as documentation so
    // the analyzer side can still find it. Lookup runs over .name only.
    static constexpr StringXRefSig AddProtobufAsBinaryStrSigs[] = {
        { "AddProtobufAsBinary", "CJSMethodArgs::AddProtobufAsBinary" },
    };

    static bool IsSteamClient64(const char* path) {
        if (!path) return false;
        const char* p1 = strrchr(path, '\\');
        const char* p2 = strrchr(path, '/');
        if (p2 && (!p1 || p2 > p1)) p1 = p2;
        const char* fn = p1 ? p1 + 1 : path;
        return (_stricmp(fn, "steamclient64.dll") == 0);
    }

    //  STEAMUI  LoadModuleWithPath hook
    LM_HOOK(LoadModuleWithPath, HMODULE, const char* path, bool flags) {
        LOG_STEAMUICH_INFO("LoadModuleWithPath called with path: {} , flags: {} [tick={}]", path, flags, GetTickCount64());
        // First steamui-mapped callback also primes the pattern fetcher worker
        // when the loader had not mapped steamui.dll at InitThread dispatch.
        DispatchSteamUiPatternFetch();
        // Wait for steamclient hooks to be installed before redirecting.
        if (!WaitForHooksInstalled(6000)) {
            LOG_STEAMUICH_WARN("LoadModuleWithPath: timed out waiting for hooks after 6000ms");
        }
        auto lmwpStart = std::chrono::steady_clock::now();
        HMODULE h = oLoadModuleWithPath(path, flags);
        auto lmwpElapsed = std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::steady_clock::now() - lmwpStart).count();
        LOG_STEAMUICH_INFO("LoadModuleWithPath({}) completed in {}ms", path, lmwpElapsed);
        if (IsSteamClient64(path)) {
            h = diversion_hModule;
            static int scCount = 0;
            HookStatus::SetSteamUiAttachState("attached", ++scCount, false);
        }
        return h;
    }

    //  STEAMUI  GetTopManager
    // The pattern publisher schema points GetTopManager directly at the
    // 2-instruction getter (mov rax, [rip+disp]; ret), so the resolved
    // address IS the function pointer. No anchor decode, no rel32 walk.

    // Fetch the CSteamUIAppController via the captured getter.
    void* ResolveController() {
        if (!oGetTopManager) return nullptr;
        void* topMgr = oGetTopManager();
        if (!topMgr) return nullptr;
        return *reinterpret_cast<void**>(static_cast<uint8_t*>(topMgr) + kControllerInTopManager);
    }

    // Synthesize a CAppOverview_Change proto with removed_appid=[appId] and
    // dispatch to every registered webhelper subscriber.
    bool EmitRemovedAppIds(void* pController, const AppId_t* ids, size_t count);

    bool EmitRemovedAppId(void* pController, AppId_t appId) {
        return EmitRemovedAppIds(pController, &appId, 1);
    }

    bool EmitRemovedAppIds(void* pController, const AppId_t* ids, size_t count) {
        if (!ids || count == 0) return false;
        alignas(8) uint8_t argsBuf[kArgsSize] = {};

        ::CAppOverview_Change msg;
        for (size_t idx = 0; idx < count; ++idx) msg.add_removed_appid(ids[idx]);
        msg.set_update_complete(true);
        oAddProtobufAsBinary(argsBuf, &msg);

        void** vecData = *reinterpret_cast<void***>(
            static_cast<uint8_t*>(pController) + kSubscriberVecOffset);
        uint32_t subCount = *reinterpret_cast<uint32_t*>(
            static_cast<uint8_t*>(pController) + kSubscriberVecSizeOffset);

        if (!vecData || subCount == 0) {
            LOG_STEAMUICH_WARN("EmitRemovedAppIds: no subscribers; count={}", count);
            return false;
        }

        for (uint32_t idx = 0; idx < subCount; ++idx) {
            void* subscriber = vecData[idx];
            if (!subscriber) continue;
            void** vtable = *reinterpret_cast<void***>(subscriber);
            auto invoke = reinterpret_cast<void(__fastcall*)(void*, void*)>(
                vtable[kSubscriberInvokeVtableSlot]);
            invoke(subscriber, argsBuf);
        }

        return true;
    }

    //  STEAMUI  MarkAppChange: member function of CUpdateManager.
    // Captures / validates g_pAppChangeSource for the RunFrame drain hook.
    LM_HOOK(MarkAppChange, void*, void* pSource, AppId_t appId, uint32 flags)
    {
        if (pSource && !g_pAppChangeSource) {
            g_pAppChangeSource = pSource;
            LOG_STEAMUICH_INFO("Captured g_pAppChangeSource (CUpdateManager) @ 0x{:X} via hkMarkAppChange",
                               reinterpret_cast<uintptr_t>(pSource));
        }
        return oMarkAppChange(pSource, appId, flags);
    }

    //  STEAMUI  FillInAppOverview: unchanged apart from removal of the
    // corrupting int64 write (offset 0x08 is StateFlags, not PurchasedTime,
    // in betterluma's CSteamApp layout). g_pAppChangeSource capture moved to
    // the MarkAppChange hook above.
    LM_HOOK(FillInAppOverview, void*, void* pThis, void* pAppOverview, void* pApp)
    {
        return oFillInAppOverview(pThis, pAppOverview, pApp);
    }

    //  STEAMUI  BuildCompleteAppOverviewChange: re-assert removed_appids
    LM_HOOK(BuildCompleteAppOverviewChange, void*, void* pController,
            void* pChange, void* optionalCallbackSlot)
    {
        void* result = oBuildCompleteAppOverviewChange(pController, pChange, optionalCallbackSlot);

        // snapshot the removed set under lock, then mutate protobuf outside
        std::vector<AppId_t> snapshot;
        {
            std::lock_guard<std::mutex> lock(g_removalMutex);
            if (!g_removedAppIds.empty())
                snapshot.assign(g_removedAppIds.begin(), g_removedAppIds.end());
        }
        if (!snapshot.empty() && pChange && oRepeatedFieldUint32_Add) {
            auto* field = static_cast<::CAppOverview_Change*>(pChange)->mutable_removed_appid();
            for (AppId_t appId : snapshot)
                oRepeatedFieldUint32_Add(field, &appId);
            LOG_STEAMUICH_DEBUG("BuildCompleteAppOverviewChange: appended {} removed_appid entries", snapshot.size());
        }
        return result;
    }

    //  STEAMUI  SerializeAchievements: ensure global percentages loaded flag is set
    using FindAppStats_t = int(__fastcall*)(void* pMap, const AppId_t* pAppId);
    inline FindAppStats_t oFindAppStats = nullptr;
    inline size_t g_appStatsMapOffset   = 0x6a8;
    inline size_t g_appStatsArrayOffset = 0x6d8;

    static void TryMarkStatsLoaded(void* pController, AppId_t appId) {
        if (!pController || appId == 0 || !oFindAppStats) return;
        __try {
            void* pMap = static_cast<uint8_t*>(pController) + g_appStatsMapOffset;
            int index = oFindAppStats(pMap, &appId);
            if (index >= 0) {
                uint8_t* pArray = *reinterpret_cast<uint8_t**>(static_cast<uint8_t*>(pController) + g_appStatsArrayOffset);
                if (pArray) {
                    uint8_t* pStatsEntry = pArray + 8 + (static_cast<size_t>(index) * 0x50);
                    pStatsEntry[0x20] = 0; // bLoading = false
                    pStatsEntry[0x21] = 1; // bUserStatsLoaded = true
                    pStatsEntry[0x22] = 1; // bGlobalStatsLoaded = true
                }
            }
        } __except (EXCEPTION_EXECUTE_HANDLER) {
        }
    }

    static AppId_t SafeGetAppId(void* pApp) {
        if (!pApp) return 0;
        AppId_t appId = 0;
        __try {
            void** vfptr = *reinterpret_cast<void***>(pApp);
            if (vfptr && vfptr[0]) {
                auto pfnGetAppID = reinterpret_cast<AppId_t(__fastcall*)(void*)>(vfptr[0]);
                appId = pfnGetAppID(pApp);
            }
            if (appId == 0) {
                uint64_t gameId = *reinterpret_cast<const uint64_t*>(static_cast<const uint8_t*>(pApp) + 8);
                appId = static_cast<AppId_t>(gameId & 0xFFFFFF);
            }
        } __except (EXCEPTION_EXECUTE_HANDLER) {
            appId = 0;
        }
        return appId;
    }

    LM_HOOK(SerializeAchievements, void*, void* pController, void* pWriter, void* pApp)
    {
        if (pController && pApp)
        {
            AppId_t appId = SafeGetAppId(pApp);
            if (appId != 0)
            {
                uint64_t gameId = 0;
                __try {
                    gameId = *reinterpret_cast<const uint64_t*>(static_cast<const uint8_t*>(pApp) + 8);
                } __except (EXCEPTION_EXECUTE_HANDLER) {
                    gameId = appId;
                }
                GlobalAchievementManager::EnsureLoaded(appId, gameId);

                if (GlobalAchievementManager::HasData(appId))
                {
                    TryMarkStatsLoaded(pController, appId);
                }
            }
        }

        return oSerializeAchievements(pController, pWriter, pApp);
    }

    //  STEAMUI  CSteamUIAppControllerRunFrame: drain live library queues
    LM_HOOK(CSteamUIAppControllerRunFrame, void*, void* pController)
    {
        static auto lastPackageRetry = std::chrono::steady_clock::now() - 1s;
        static uint32_t runFrameRetryLogs = 0;
        auto now = std::chrono::steady_clock::now();
        if (now - lastPackageRetry >= 1s) {
            lastPackageRetry = now;
            SteamCapture::TryStartupPackageInjection("steamui-runframe-retry");
            ++runFrameRetryLogs;
            if (runFrameRetryLogs == 1 || runFrameRetryLogs % 30 == 0) {
                LOG_STEAMUICH_DEBUG("RunFrame: startup package retry tick={}", runFrameRetryLogs);
            }
        }

        if (oMarkAppChange && g_pAppChangeSource)
        {
            std::vector<AppId_t> drainingRemovals;
            std::vector<AppId_t> drainingTouches;
            {
                std::lock_guard<std::mutex> lock(g_removalMutex);
                drainingRemovals.swap(g_pendingRemovals);
                drainingTouches.swap(g_pendingTouches);
            }
            if (oGetAppByID)
            {
                for (AppId_t appId : drainingRemovals)
                {
                    if (LuaLoader::IsOwned(appId))
                    {
                        LOG_STEAMUICH_DEBUG("RunFrame: appId {} is owned again, skipping removal", appId);
                        continue;
                    }
                    if (CSteamApp* pApp = static_cast<CSteamApp*>(oGetAppByID(pController, appId, false)))
                    {
                        pApp->OwnershipFlags = k_EAppOwnershipFlags_None;
                        if (pApp->AppStateFlags == k_EAppStateUninstalled)
                        {
                            std::lock_guard<std::mutex> lock(g_removalMutex);
                            g_removedAppIds.insert(appId);
                        }
                    }
                    oMarkAppChange(g_pAppChangeSource, appId, 2); // AppInfoOrConfig
                }
            }
            else if (!drainingRemovals.empty())
            {
                std::lock_guard<std::mutex> lock(g_removalMutex);
                g_pendingRemovals.insert(g_pendingRemovals.end(),
                                         drainingRemovals.begin(),
                                         drainingRemovals.end());
            }
            for (AppId_t appId : drainingTouches)
            {
                {
                    std::lock_guard<std::mutex> lock(g_removalMutex);
                    g_removedAppIds.erase(appId);
                }
                oMarkAppChange(g_pAppChangeSource, appId, 2); // AppInfoOrConfig
                LOG_STEAMUICH_DEBUG("RunFrame: appId {} touched for live library refresh", appId);
            }
        }
        return oCSteamUIAppControllerRunFrame(pController);
    }

} // anonymous namespace

namespace SteamUI {

    // The LM_* macros target diversion_hModule (steamclient64.dll). SteamUI
    // hooks live in steamui.dll, so the install path resolves through
    // ByteSearch(hSteamUI, ...) directly and runs the Detours attach plus
    // HookStatus reporting by hand. The shape mirrors what LM_INSTALL and
    // LM_BIND expand to, just with a different module handle.
    void CoreHook() {
        std::lock_guard<std::mutex> coreLock(g_coreHookMutex);
        if (g_coreHookInstalled) {
            LOG_STEAMUICH_DEBUG("CoreHook: already installed");
            return;
        }

        HMODULE hSteamUI = GetModuleHandleA("steamui.dll");
        if (!hSteamUI) {
            LOG_STEAMUICH_WARN("steamui.dll not loaded; SteamUI hooks disabled");
            HookStatus::SetSteamUiAttachState("waiting-steamui", 0, false);
            return;
        }

        PatternFetcher::AssociateModule(hSteamUI, "steamui");
        const auto& patternState = PatternFetcher::Get(hSteamUI);
        if (!patternState.ok) {
            LOG_STEAMUICH_WARN("CoreHook: steamui patterns unavailable; waiting for retry");
            HookStatus::SetSteamUiAttachState("waiting-steamui-pattern", 0, false);
            return;
        }

        LM_TX_BEGIN();
        {
            void* _p_ = ByteSearch(hSteamUI, "LoadModuleWithPath");
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Hook: LoadModuleWithPath attached @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(_p_));
                oLoadModuleWithPath = reinterpret_cast<LoadModuleWithPath_t>(_p_);
                DetourAttach(reinterpret_cast<PVOID*>(&oLoadModuleWithPath),
                             reinterpret_cast<PVOID>(hkLoadModuleWithPath));
                HookStatus::RecordInstalled();
                HookStatus::SetSteamUiAttachState("hook_installed", 0, false);
            } else {
                LOG_STEAMUICH_WARN("Hook: LoadModuleWithPath skipped (TOML entry missing for steamui)");
                HookStatus::RecordMissed("LoadModuleWithPath");
            }
        }
        {
            void* _p_ = ByteSearch(hSteamUI, "FillInAppOverview");
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Hook: FillInAppOverview attached @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(_p_));
                oFillInAppOverview = reinterpret_cast<FillInAppOverview_t>(_p_);
                DetourAttach(reinterpret_cast<PVOID*>(&oFillInAppOverview),
                             reinterpret_cast<PVOID>(hkFillInAppOverview));
                HookStatus::RecordInstalled();
            } else {
                LOG_STEAMUICH_WARN("Hook: FillInAppOverview skipped (TOML entry missing)");
                HookStatus::RecordMissed("FillInAppOverview");
            }
        }
        {
            void* _p_ = ByteSearch(hSteamUI, "BuildCompleteAppOverviewChange");
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Hook: BuildCompleteAppOverviewChange attached @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(_p_));
                oBuildCompleteAppOverviewChange = reinterpret_cast<BuildCompleteAppOverviewChange_t>(_p_);
                DetourAttach(reinterpret_cast<PVOID*>(&oBuildCompleteAppOverviewChange),
                             reinterpret_cast<PVOID>(hkBuildCompleteAppOverviewChange));
                HookStatus::RecordInstalled();
            } else {
                LOG_STEAMUICH_WARN("Hook: BuildCompleteAppOverviewChange skipped (TOML entry missing)");
                HookStatus::RecordMissed("BuildCompleteAppOverviewChange");
            }
        }
        {
            void* _p_ = ByteSearch(hSteamUI, "CSteamUIAppControllerRunFrame");
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Hook: CSteamUIAppControllerRunFrame attached @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(_p_));
                oCSteamUIAppControllerRunFrame = reinterpret_cast<CSteamUIAppControllerRunFrame_t>(_p_);
                DetourAttach(reinterpret_cast<PVOID*>(&oCSteamUIAppControllerRunFrame),
                             reinterpret_cast<PVOID>(hkCSteamUIAppControllerRunFrame));
                HookStatus::RecordInstalled();
            } else {
                LOG_STEAMUICH_WARN("Hook: CSteamUIAppControllerRunFrame skipped (TOML entry missing)");
                HookStatus::RecordMissed("CSteamUIAppControllerRunFrame");
            }
        }
        // MarkAppChange hook captures g_pAppChangeSource for RunFrame drain
        {
            void* _p_ = ByteSearch(hSteamUI, "MarkAppChange");
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Hook: MarkAppChange attached @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(_p_));
                oMarkAppChange = reinterpret_cast<MarkAppChange_t>(_p_);
                DetourAttach(reinterpret_cast<PVOID*>(&oMarkAppChange),
                             reinterpret_cast<PVOID>(hkMarkAppChange));
                HookStatus::RecordInstalled();

                // Dynamically resolve g_pAppChangeSource (&g_UpdateManager) from MarkAppChange callsite in .text
                if (!g_pAppChangeSource) {
                    auto baseBytes = reinterpret_cast<const uint8_t*>(hSteamUI);
                    auto dosHeader = reinterpret_cast<const IMAGE_DOS_HEADER*>(baseBytes);
                    if (dosHeader->e_magic == IMAGE_DOS_SIGNATURE) {
                        auto ntHeaders = reinterpret_cast<const IMAGE_NT_HEADERS*>(baseBytes + dosHeader->e_lfanew);
                        if (ntHeaders->Signature == IMAGE_NT_SIGNATURE) {
                            auto sectionHeader = IMAGE_FIRST_SECTION(ntHeaders);
                            const uint8_t* textStart = nullptr;
                            size_t textSize = 0;
                            uintptr_t dataStart = 0;
                            uintptr_t dataEnd = 0;

                            for (WORD i = 0; i < ntHeaders->FileHeader.NumberOfSections; ++i) {
                                if (memcmp(sectionHeader[i].Name, ".text", 5) == 0) {
                                    textStart = baseBytes + sectionHeader[i].VirtualAddress;
                                    textSize = sectionHeader[i].Misc.VirtualSize;
                                } else if (memcmp(sectionHeader[i].Name, ".data", 5) == 0) {
                                    dataStart = reinterpret_cast<uintptr_t>(baseBytes) + sectionHeader[i].VirtualAddress;
                                    dataEnd = dataStart + sectionHeader[i].Misc.VirtualSize;
                                }
                            }

                            if (textStart && textSize > 5) {
                                for (size_t i = 0; i < textSize - 5; ++i) {
                                    if (textStart[i] == 0xE8) {
                                        int32_t rel = *reinterpret_cast<const int32_t*>(textStart + i + 1);
                                        const uint8_t* callDest = textStart + i + 5 + rel;
                                        if (callDest == reinterpret_cast<const uint8_t*>(_p_)) {
                                            for (size_t back = 1; back <= 32 && i >= back; ++back) {
                                                size_t pos = i - back;
                                                if (textStart[pos] == 0x48 && textStart[pos + 1] == 0x8D && textStart[pos + 2] == 0x0D) {
                                                    int32_t disp = *reinterpret_cast<const int32_t*>(textStart + pos + 3);
                                                    uintptr_t target = reinterpret_cast<uintptr_t>(textStart + pos + 7 + disp);
                                                    if (target >= dataStart && target < dataEnd) {
                                                        g_pAppChangeSource = reinterpret_cast<void*>(target);
                                                        LOG_STEAMUICH_INFO("Resolve: g_pAppChangeSource (CUpdateManager) bound @ 0x{:X}", target);
                                                        break;
                                                    }
                                                }
                                            }
                                            if (g_pAppChangeSource) break;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            } else {
                LOG_STEAMUICH_WARN("Hook: MarkAppChange skipped (TOML entry missing)");
                HookStatus::RecordMissed("MarkAppChange");
            }
        }
        {
            void* pSerialize = StringFind::FindFunction(hSteamUI, "vecAchievedHidden");
            if (!pSerialize) {
                pSerialize = StringFind::FindFunction(hSteamUI, "vecHighlight");
            }
            if (pSerialize) {
                LOG_STEAMUICH_DEBUG("Hook: SerializeAchievements attached @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(pSerialize));
                oSerializeAchievements = reinterpret_cast<SerializeAchievements_t>(pSerialize);
                DetourAttach(reinterpret_cast<PVOID*>(&oSerializeAchievements),
                             reinterpret_cast<PVOID>(hkSerializeAchievements));
                HookStatus::RecordInstalled();

                // Scan for the call to FindAppStats inside SerializeAchievements
                const uint8_t* pCode = reinterpret_cast<const uint8_t*>(pSerialize);
                for (size_t i = 0; i < 0x100; ++i) {
                    if (pCode[i] == 0xE8 && pCode[i + 5] == 0x83 && pCode[i + 6] == 0xF8 && pCode[i + 7] == 0xFF) {
                        int32_t disp = *reinterpret_cast<const int32_t*>(pCode + i + 1);
                        oFindAppStats = reinterpret_cast<FindAppStats_t>(const_cast<uint8_t*>(pCode + i + 5 + disp));
                        LOG_STEAMUICH_INFO("Resolve: FindAppStats bound @ 0x{:X}",
                                            reinterpret_cast<uintptr_t>(oFindAppStats));

                        // Dynamically extract map and array offsets from the surrounding instructions
                        for (size_t back = 1; back <= 32 && i >= back; ++back) {
                            if (pCode[i - back] == 0x48 && pCode[i - back + 1] == 0x8D && (pCode[i - back + 2] & 0xC7) == 0x87) {
                                g_appStatsMapOffset = *reinterpret_cast<const uint32_t*>(pCode + i - back + 3);
                                LOG_STEAMUICH_DEBUG("Resolve: g_appStatsMapOffset bound to 0x{:X}", g_appStatsMapOffset);
                                break;
                            }
                        }
                        if (pCode[i + 8] == 0x0F && pCode[i + 9] == 0x84) {
                            size_t afterJe = i + 14;
                            if (pCode[afterJe] == 0x48 && pCode[afterJe + 1] == 0x8B && (pCode[afterJe + 2] & 0xC7) == 0x87) {
                                g_appStatsArrayOffset = *reinterpret_cast<const uint32_t*>(pCode + afterJe + 3);
                                LOG_STEAMUICH_DEBUG("Resolve: g_appStatsArrayOffset bound to 0x{:X}", g_appStatsArrayOffset);
                            }
                        }
                        break;
                    }
                }
            } else {
                LOG_STEAMUICH_WARN("Hook: SerializeAchievements skipped (vecAchievedHidden xref missed)");
                HookStatus::RecordMissed("SerializeAchievements");
            }
        }
        LM_TX_COMMIT();

        // Helper resolves (no Detours attach, just bind the trampoline slot).
        {
            void* _p_ = ByteSearch(hSteamUI, "GetAppByID");
            oGetAppByID = reinterpret_cast<GetAppByID_t>(_p_);
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Resolve: GetAppByID bound @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(_p_));
                HookStatus::RecordInstalled();
            } else {
                LOG_STEAMUICH_WARN("Resolve: GetAppByID skipped (TOML entry missing for steamui)");
                HookStatus::RecordMissed("GetAppByID");
            }
        }

        // AddProtobufAsBinary: walk the StringXRefSig array and use the first
        // candidate name that resolves through the steamui TOML. Each .name
        // is a TOML lookup key; .xref is documentation only.
        {
            void* _p_ = nullptr;
            const char* _matched_ = nullptr;
            for (const auto& _s_ : AddProtobufAsBinaryStrSigs) {
                _p_ = ByteSearch(hSteamUI, _s_.name);
                if (_p_) { _matched_ = _s_.name; break; }
            }
            oAddProtobufAsBinary = reinterpret_cast<AddProtobufAsBinary_t>(_p_);
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Resolve: AddProtobufAsBinary bound via TOML key \"{}\" @ 0x{:X}",
                                    _matched_, reinterpret_cast<uintptr_t>(_p_));
                HookStatus::RecordInstalled();
            } else {
                LOG_STEAMUICH_WARN("Resolve: AddProtobufAsBinary skipped (no TOML key in array resolved)");
                HookStatus::RecordMissed("AddProtobufAsBinary");
            }
        }

        // GetTopManager: per the canonical pattern publisher schema, rva
        // points directly at the 2-instruction getter
        // (mov rax, [rip+disp]; ret). No rel32 decode needed; the resolved
        // address IS the function pointer we call.
        {
            void* _p_ = ByteSearch(hSteamUI, "GetTopManager");
            oGetTopManager = reinterpret_cast<GetTopManager_t>(_p_);
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Resolve: GetTopManager bound @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(_p_));
                HookStatus::RecordInstalled();
            } else {
                LOG_STEAMUICH_WARN("Resolve: GetTopManager skipped (TOML entry missing for steamui)");
                HookStatus::RecordMissed("GetTopManager");
            }
        }

        {
            void* _p_ = ByteSearch(hSteamUI, "RepeatedFieldUint32_Add");
            oRepeatedFieldUint32_Add = reinterpret_cast<RepeatedFieldUint32_Add_t>(_p_);
            if (_p_) {
                LOG_STEAMUICH_DEBUG("Resolve: RepeatedFieldUint32_Add bound @ 0x{:X}",
                                    reinterpret_cast<uintptr_t>(_p_));
                HookStatus::RecordInstalled();
            } else {
                LOG_STEAMUICH_WARN("Resolve: RepeatedFieldUint32_Add skipped (TOML entry missing)");
                HookStatus::RecordMissed("RepeatedFieldUint32_Add");
            }
        }

        LOG_STEAMUICH_INFO("Install: GetAppByID={}, AddProtobufAsBinary={}, GetTopManager={}",
                         reinterpret_cast<void*>(oGetAppByID),
                         reinterpret_cast<void*>(oAddProtobufAsBinary),
                         reinterpret_cast<void*>(oGetTopManager));
        g_coreHookInstalled = true;
        HookStatus::SetSteamUiAttachState("installed", 0, false);
    }

    void CoreUnhook() {
        std::lock_guard<std::mutex> coreLock(g_coreHookMutex);
        if (!g_coreHookInstalled) return;
        LM_TX_BEGIN();
        LM_REMOVE(LoadModuleWithPath);
        LM_REMOVE(FillInAppOverview);
        LM_REMOVE(BuildCompleteAppOverviewChange);
        LM_REMOVE(CSteamUIAppControllerRunFrame);
        LM_REMOVE(MarkAppChange);
        LM_REMOVE(SerializeAchievements);
        LM_TX_COMMIT();

        oAddProtobufAsBinary           = nullptr;
        oGetAppByID                    = nullptr;
        oGetTopManager                 = nullptr;
        oFillInAppOverview             = nullptr;
        oBuildCompleteAppOverviewChange = nullptr;
        oCSteamUIAppControllerRunFrame  = nullptr;
        oRepeatedFieldUint32_Add       = nullptr;
        oFindAppStats                  = nullptr;
        g_pAppChangeSource             = nullptr;
        {
            std::lock_guard<std::mutex> lock(g_removalMutex);
            g_pendingRemovals.clear();
            g_pendingTouches.clear();
            g_removedAppIds.clear();
        }
        g_coreHookInstalled = false;
    }

    void RemoveAppOverview(AppId_t appId) {
        if (!oAddProtobufAsBinary || !oGetTopManager || !oGetAppByID) {
            LOG_STEAMUICH_WARN("RemoveAppOverview: primitives unresolved; appId={}", appId);
            return;
        }

        // Skip eviction for apps Steam already provides. The dual-account
        // refresh path was tearing them out of the library card view because
        // every appid in the package vector got the eviction treatment.
        if (LuaLoader::IsSteamProvidedApp(appId)) {
            LOG_STEAMUICH_DEBUG("RemoveAppOverview: appId={} is Steam-provided; skipping eviction", appId);
            return;
        }

        void* pController = ResolveController();
        if (!pController) {
            LOG_STEAMUICH_WARN("RemoveAppOverview: controller singleton not initialized; appId={}", appId);
            return;
        }

        // Clear the host-side CSteamApp owned flag if a CSteamApp exists for
        // this id. Sub-depots (e.g. HL1's 221-234) won't have one, so just
        // skip the flag-clear and still emit the removal so any stale
        // subscriber state for the id gets cleaned up.
        if (void* pApp = oGetAppByID(pController, appId, /*create=*/false)) {
            *reinterpret_cast<uint32_t*>(static_cast<uint8_t*>(pApp) + kCSteamAppOwnedFlagOffset) &= ~1u;
        }

        if (!EmitRemovedAppId(pController, appId)) return;

        LOG_STEAMUICH_INFO("RemoveAppOverview: appId={} done", appId);
    }

    void QueueLibraryRemoval(AppId_t appId) {
        std::lock_guard<std::mutex> lock(g_removalMutex);
        if (std::find(g_pendingRemovals.begin(), g_pendingRemovals.end(), appId) == g_pendingRemovals.end())
            g_pendingRemovals.push_back(appId);
        LOG_STEAMUICH_DEBUG("QueueLibraryRemoval: appId={} queued", appId);
    }

    void QueueLibraryTouch(AppId_t appId) {
        std::lock_guard<std::mutex> lock(g_removalMutex);
        auto removeIt = std::find(g_pendingRemovals.begin(), g_pendingRemovals.end(), appId);
        if (removeIt != g_pendingRemovals.end()) {
            *removeIt = std::move(g_pendingRemovals.back());
            g_pendingRemovals.pop_back();
        }
        g_removedAppIds.erase(appId);
        if (std::find(g_pendingTouches.begin(), g_pendingTouches.end(), appId) == g_pendingTouches.end())
            g_pendingTouches.push_back(appId);
        LOG_STEAMUICH_DEBUG("QueueLibraryTouch: appId={} queued", appId);
    }

    void CancelLibraryRemoval(AppId_t appId) {
        std::lock_guard<std::mutex> lock(g_removalMutex);
        auto it = std::find(g_pendingRemovals.begin(), g_pendingRemovals.end(), appId);
        if (it != g_pendingRemovals.end()) {
            *it = std::move(g_pendingRemovals.back());
            g_pendingRemovals.pop_back();
            g_removedAppIds.erase(appId);
            LOG_STEAMUICH_DEBUG("CancelLibraryRemoval: appId={} removed from queue and removed set", appId);
        } else {
            g_removedAppIds.erase(appId);
        }
    }

} // namespace SteamUI
